[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
proj = "BjRSHo9aArH2X9WGAz49BLjEEQq9oM1uobsF54EVJkXA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marcho/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
